title: AMS Github Website
email: joyce.liyue@yale.edu
description: >-
  A lightweight public website for browsing and displaying the Anthology of Chinese Folk Songs metadata.
baseurl: "/AMS-Github-Website"
url: "https://jliyue.github.io"
github_username: jliyue

theme: minima